# Generated by Django 4.1.4 on 2023-05-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_githublink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='githublink',
            field=models.CharField(blank=True, default='github', max_length=200),
        ),
    ]
