# Generated by Django 4.1.4 on 2023-05-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('event_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
