# Generated by Django 4.1.4 on 2023-04-01 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 1, 14, 36, 45, 380984, tzinfo=datetime.timezone.utc), null=True)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('event_picture', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
