# Generated by Django 4.1.4 on 2023-04-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
