# Generated by Django 4.1.4 on 2023-05-21 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('EndDate', models.DateField()),
                ('status', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('patentNo', models.IntegerField(blank=True, null=True)),
                ('AcademicYear', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=20)),
                ('patent_info', models.TextField(blank=True, default=' ', null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField()),
                ('Storage_link', models.URLField(blank=True, null=True)),
                ('type', models.CharField(default='public', max_length=10)),
                ('description', models.TextField()),
                ('aicte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aicte_project', to=settings.AUTH_USER_MODEL)),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dean_project', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.domain')),
                ('guid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guid_project', to=settings.AUTH_USER_MODEL)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_project', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('EndDate', models.DateField()),
                ('status', models.CharField(max_length=7)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.goal')),
            ],
        ),
        migrations.CreateModel(
            name='hodrecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodrecord', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodprojectrecord', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='HodApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='guidrecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidrecord', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidprojectrecord', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Group_project', to='project.project')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user2', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user3', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deanrecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deanrecord', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deanprojectrecord', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='DeanApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AicteMember', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AicteMember', to=settings.AUTH_USER_MODEL)),
                ('dean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dean', to=settings.AUTH_USER_MODEL)),
                ('guid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guid', to=settings.AUTH_USER_MODEL)),
                ('hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved_guid', models.BooleanField(default=False)),
                ('is_aicte_approved', models.BooleanField(default=False)),
                ('is_hod_approved', models.BooleanField(default=False)),
                ('is_dean_approved', models.BooleanField(default=False)),
                ('is_teacher_approved', models.BooleanField(default=False)),
                ('description_guid', models.CharField(max_length=1000, null=True)),
                ('description_hod', models.CharField(max_length=1000, null=True)),
                ('description_dean', models.CharField(max_length=1000, null=True)),
                ('description_aicte', models.CharField(max_length=1000, null=True)),
                ('description_teacher', models.CharField(max_length=1000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='aicterecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aicte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aicterecord', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aicteprojectrecord', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='AicteApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Aicte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name',), name='Unique_entries_project'),
        ),
        migrations.AddConstraint(
            model_name='hodrecord',
            constraint=models.UniqueConstraint(fields=('hod', 'project'), name='hodrecordunique'),
        ),
        migrations.AddConstraint(
            model_name='hodapproval',
            constraint=models.UniqueConstraint(fields=('hod', 'project'), name='uniqueHodApproval'),
        ),
        migrations.AddConstraint(
            model_name='guidrecord',
            constraint=models.UniqueConstraint(fields=('guid', 'project'), name='guidrecordunique'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('project',), name='group_project'),
        ),
        migrations.AddConstraint(
            model_name='deanrecord',
            constraint=models.UniqueConstraint(fields=('dean', 'project'), name='deanrecordunique'),
        ),
        migrations.AddConstraint(
            model_name='deanapproval',
            constraint=models.UniqueConstraint(fields=('Dean', 'project'), name='uniqueDeanApproval'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('guid', 'hod', 'dean', 'AicteMember', 'project'), name='Unique_entries_assigned'),
        ),
        migrations.AddConstraint(
            model_name='aicterecord',
            constraint=models.UniqueConstraint(fields=('aicte', 'project'), name='aicterecordunique'),
        ),
        migrations.AddConstraint(
            model_name='aicteapproval',
            constraint=models.UniqueConstraint(fields=('Aicte', 'project'), name='uniqueAicteApproval'),
        ),
    ]
