# Generated by Django 4.1.4 on 2023-05-20 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aicte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aicte_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dean_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.domain'),
        ),
        migrations.AddField(
            model_name='project',
            name='guid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guid_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.goal'),
        ),
        migrations.AddField(
            model_name='hodrecord',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodrecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hodrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodprojectrecord', to='project.project'),
        ),
        migrations.AddField(
            model_name='hodapproval',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hodapproval',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='guidrecord',
            name='guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidrecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidprojectrecord', to='project.project'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Group_project', to='project.project'),
        ),
        migrations.AddField(
            model_name='group',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='user3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='user4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deanrecord',
            name='dean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deanrecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deanrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deanprojectrecord', to='project.project'),
        ),
        migrations.AddField(
            model_name='deanapproval',
            name='Dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deanapproval',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='AicteMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AicteMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='dean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dean', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='guid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='approve',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='aicterecord',
            name='aicte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aicterecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aicterecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aicteprojectrecord', to='project.project'),
        ),
        migrations.AddField(
            model_name='aicteapproval',
            name='Aicte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aicteapproval',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name',), name='Unique_entries_project'),
        ),
        migrations.AddConstraint(
            model_name='hodrecord',
            constraint=models.UniqueConstraint(fields=('hod', 'project'), name='hodrecordunique'),
        ),
        migrations.AddConstraint(
            model_name='hodapproval',
            constraint=models.UniqueConstraint(fields=('hod', 'project'), name='uniqueHodApproval'),
        ),
        migrations.AddConstraint(
            model_name='guidrecord',
            constraint=models.UniqueConstraint(fields=('guid', 'project'), name='guidrecordunique'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('project',), name='group_project'),
        ),
        migrations.AddConstraint(
            model_name='deanrecord',
            constraint=models.UniqueConstraint(fields=('dean', 'project'), name='deanrecordunique'),
        ),
        migrations.AddConstraint(
            model_name='deanapproval',
            constraint=models.UniqueConstraint(fields=('Dean', 'project'), name='uniqueDeanApproval'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('guid', 'hod', 'dean', 'AicteMember', 'project'), name='Unique_entries_assigned'),
        ),
        migrations.AddConstraint(
            model_name='aicterecord',
            constraint=models.UniqueConstraint(fields=('aicte', 'project'), name='aicterecordunique'),
        ),
        migrations.AddConstraint(
            model_name='aicteapproval',
            constraint=models.UniqueConstraint(fields=('Aicte', 'project'), name='uniqueAicteApproval'),
        ),
    ]
