# Generated by Django 4.1.4 on 2023-05-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='group',
            name='Unique_entries',
        ),
        migrations.AddField(
            model_name='approve',
            name='description_teacher',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='approve',
            name='is_teacher_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('guid', 'teacher', 'hod', 'dean', 'AicteMember', 'project'), name='Unique_entries_assigned'),
        ),
    ]
