# Generated by Django 4.1.4 on 2023-04-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.AddField(
            model_name='project',
            name='Storage_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='public', max_length=10),
        ),
    ]
