# Generated by Django 4.1.4 on 2023-04-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_goal_project_storage_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='group',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='project',
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('name', 'student', 'project'), name='Unique_entries'),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
