# Generated by Django 4.1.4 on 2023-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isapproval',
            field=models.BooleanField(default=False),
        ),
    ]
