# Generated by Django 4.1.4 on 2023-05-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_isapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isapproval',
            field=models.CharField(default='Not Approved', max_length=100),
        ),
    ]
