# Generated by Django 4.1.4 on 2023-04-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_approval_group_remove_approval_guid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='guid',
        ),
    ]
